1.Write a function to compute 5/0 and use try/except to catch the exceptions.


In [4]:

def division():
    return 5/0
try:  
    division()
except:
    print("value of b should not be 0 which results in zerodivisonerror")

value of b should not be 0 which results in zerodivisonerror


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


Output should come as below:
    
    
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [5]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i +" "+ j + " "+k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task2

1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 

In [9]:
def vander_matrix(inpvector, n, increasing=False):
    
    if not increasing:
        out_matx = np.array([x**(n-1-i) for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    elif increasing:
        out_matx = np.array([x**i for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    
    return out_matx

In [13]:
import numpy as np
inputvector = np.array([1,2,3,4,5])
outmat = 5 #number of columns of output matrix
out_matx_dec_order = vander_matrix(inputvector,outmat,False)
out_matx_inc_order = vander_matrix(inputvector,outmat,True)


print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",outmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",out_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",out_matx_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

